DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Classes;
DROP TABLE IF EXISTS Teacher;
DROP TABLE IF EXISTS Subjects;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Funding;
DROP TABLE IF EXISTS Olympiads;
DROP TABLE IF EXISTS Exam_grades;
