use hurtownie

DROP TABLE IF EXISTS Classes;
DROP TABLE IF EXISTS Funding;
DROP TABLE IF EXISTS Exam;
DROP TABLE IF EXISTS Subjects;
DROP TABLE IF EXISTS Teacher;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Date_;
DROP TABLE IF EXISTS Time_;

-- DDs
DROP TABLE IF EXISTS Transaction_;
DROP TABLE IF EXISTS Partner_;
DROP TABLE IF EXISTS Examinator;